name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
    - uses: leafo/gh-actions-luarocks@v4.0.0
    
    - name: build
      run: |
        luarocks install busted
        luarocks install luacheck
    - name: lint
      run: luacheck ./src

    - name: test
      run: busted
